FROM centos

RUN yum update -y \
 && yum install -y http://www.city-fan.org/ftp/contrib/yum-repo/city-fan.org-release-2-1.rhel7.noarch.rpm \
                   epel-release \
                   rpm* rpm-build rpmdev* \
                   gcc \
                   krb5-devel \
                   openldap-devel \
                   groff \
                   make \
                   openssl-devel \
                   zlib-devel \
                   gnutls-utils \
                   openssh-clients \
                   openssh-server \
                   stunnel \
 \
 && yum install -y --enablerepo="city-fan*" \
                   libmetalink-devel \
                   libnghttp2-devel \
                   nghttp2 \
                   libpsl-devel \
                   libssh2-devel \
                   perl-IO-Compress \
                   perl-Digest-MD5 \
 \
 && rpm -i http://www.city-fan.org/ftp/contrib/yum-repo/rhel7/source/curl-7.65.1-1.0.cf.rhel7.src.rpm \
 && cd /root/rpmbuild/SPECS \
 && rpmbuild --without nss -bb curl.spec \
 && cd - \
 && mv -f /root/rpmbuild/RPMS/x86_64/*.rpm / \
 && yum remove -y libmetalink-devel \
                  libnghttp2-devel \
                  libpsl-devel \
                  libssh2-devel \
                  nghttp2 \
                  perl-Digest-MD5 \
                  perl-IO-Compress \
                  c-ares \
                  libev \
                  libicu \
                  libmetalink \
                  libnghttp2 \
                  libpsl \
                  perl-Compress-Raw-Bzip2 \
                  perl-Compress-Raw-Zlib \
                  perl-Digest \
 && yum remove -y city-fan.org-release \
                  epel-release \
                  gcc \
                  gnutls-utils \
                  groff \
                  krb5-devel \
                  make \
                  openldap-devel \
                  openssh-clients \
                  openssh-server \
                  openssl-devel \
                  rpm-apidocs \
                  rpm-build \
                  rpm-cron \
                  rpm-devel \
                  rpm-plugin-systemd-inhibit \
                  rpm-sign \
                  rpmdevtools \
                  rpmemd \
                  rpmlint \
                  stunnel \
                  zlib-devel \
                  autogen-libopts \
                  bzip2 \
                  cpp \
                  cronie \
                  cronie-anacron \
                  crontabs \
                  cyrus-sasl \
                  cyrus-sasl-devel \
                  daxctl-libs \
                  desktop-file-utils \
                  dwz \
                  elfutils \
                  emacs-filesystem \
                  file \
                  fipscheck \
                  fipscheck-lib \
                  gdb \
                  glibc-devel \
                  glibc-headers \
                  gnutls \
                  gnutls-dane \
                  groff-base \
                  hwdata \
                  infinipath-psm \
                  initscripts \
                  iproute \
                  iptables \
                  kernel-header \
                  keyutils-libs-devel \
                  less \
                  libcom_err-devel \
                  libedit \
                  libevent \
                  libfabric \
                  libgomp \
                  libibverbs \
                  libkadm5 \
                  libmnl \
                  libmpc \
                  libnetfilter_conntrack \
                  libnfnetlink \
                  libnl3 \
                  libpipeline \
                  libpmem \
                  libpsm2 \
                  librdmacm \
                  libselinux-devel \
                  libsepol-devel \
                  libverto-devel \
                  logrotate \
                  man-db \
                  mpfr \
                  ndctl-libs \
                  nettle \
                  numactl-libs \
                  openssh \
                  openssl \
                  patch \
                  pciutils \
                  pciutils-libs \
                  pcre-devel \
                  perl \
                  perl-Carp \
                  perl-Encode \
                  perl-Exporter \
                  perl-File-Path \
                  perl-File-Temp \
                  perl-Filter \
                  perl-Getopt-Long \
                  perl-HTTP-Tiny \
                  perl-PathTools \
                  perl-Pod-Escapes \
                  perl-Pod-Perldoc \
                  perl-Pod-Simple \
                  perl-Pod-Usage \
                  perl-Scalar-List-Utils \
                  perl-Socket \
                  perl-Storable \
                  perl-Text-ParseWords \
                  perl-Thread-Queue \
                  perl-Time-HiRes \
                  perl-Time-Local \
                  perl-constant \
                  perl-libs \
                  perl-macros \
                  perl-parent \
                  perl-podlators \
                  perl-srpm-macros \
                  perl-threads \
                  perl-threads-shared \
                  popt-devel \
                  rdma-core \
                  redhat-rpm-config \
                  sysvinit-tools \
                  tcp_wrappers-libs \
                  trousers \
                  unbound-libs \
                  unzip \
                  zip \
 && rm -rf /root/rpmbuild
